import { NextResponse } from 'next/server';

export async function GET(request: Request) {
    try {
        const url = new URL(request.url);
        const gameId = url.searchParams.get('gameId');

        const authHeader = request.headers.get('Authorization');
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const CORE_SERVER_SCRIPT = `-- RoLink Server Core Component
-- This script acts as the main bridge between your Roblox Game and RoLink Servers.
-- DO NOT EDIT THIS FILE DIRECTLY. It will be overwritten during Plugin Syncs.

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")
local ServerScriptService = game:GetService("ServerScriptService")

local ROLINK_BASE_URL = "https://ro-link.com/api/v1"

local function getApiKey()
    local config = ServerScriptService:FindFirstChild("RoLinkConfig")
    if config then
        local key = config:GetAttribute("ApiKey")
        if key then return key end
    end
    warn("[RoLink] Missing API Key! Are you sure you synced the plugin?")
    return nil
end

local function handlePlayerJoin(player)
    local apiKey = getApiKey()
    if not apiKey then return end

    local success, response = pcall(function()
        return HttpService:RequestAsync({
            Url = ROLINK_BASE_URL .. "/roblox/user/" .. player.UserId .. "/verify",
            Method = "GET",
            Headers = {
                ["Authorization"] = "Bearer " .. apiKey,
                ["Content-Type"] = "application/json"
            }
        })
    end)

    if success and response.StatusCode == 200 then
        local data = HttpService:JSONDecode(response.Body)
        if data.verified then
            print("[RoLink] " .. player.Name .. " is verified via RoLink!")
            -- You can assign tools, Teams, or Group Roles based on this state
        else
            warn("[RoLink] " .. player.Name .. " is NOT verified.")
        end
    else
        warn("[RoLink] Failed to fetch verification data for " .. player.Name)
    end
end

Players.PlayerAdded:Connect(handlePlayerJoin)
print("[RoLink] Server Core initialized successfully.")
`;

        const CORE_CLIENT_SCRIPT = `-- RoLink Client Core Component
-- Minimal footprint to handle UI prompts if needed via RoLink.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local player = Players.LocalPlayer

print("[RoLink] Client Core initialized for " .. player.Name)
-- Extend this file if UI verification prompts or CAPTCHAs are needed.
`;

        const ROLINK_API_MODULE = `-- RoLink API Module
-- You can require this module in your own server scripts to manually pull data.

local HttpService = game:GetService("HttpService")
local ServerScriptService = game:GetService("ServerScriptService")

local RoLinkAPI = {}
local ROLINK_BASE_URL = "https://ro-link.com/api/v1"

function RoLinkAPI:GetApiKey()
    local config = ServerScriptService:FindFirstChild("RoLinkConfig")
    return config and config:GetAttribute("ApiKey") or nil
end

function RoLinkAPI:FetchUser(userId)
    local apiKey = self:GetApiKey()
    if not apiKey then return nil, "No API Key" end

    local success, response = pcall(function()
        return HttpService:RequestAsync({
            Url = ROLINK_BASE_URL .. "/roblox/user/" .. userId .. "/data",
            Method = "GET",
            Headers = { ["Authorization"] = "Bearer " .. apiKey }
        })
    end)

    if success and response.StatusCode == 200 then
        return HttpService:JSONDecode(response.Body), nil
    else
        return nil, "HTTP Error " .. tostring(response.StatusCode)
    end
end

return RoLinkAPI
`;

        const scripts = [
            {
                name: "RoLinkServerCore",
                type: "Script",
                service: "ServerScriptService",
                version: "1.0.1",
                source: CORE_SERVER_SCRIPT
            },
            {
                name: "RoLinkClientCore",
                type: "LocalScript",
                service: "StarterPlayerScripts",
                version: "1.0.1",
                source: CORE_CLIENT_SCRIPT
            },
            {
                name: "RoLinkAPI",
                type: "ModuleScript",
                service: "ReplicatedStorage",
                version: "1.0.1",
                source: ROLINK_API_MODULE
            }
        ];

        return NextResponse.json({ scripts });
    } catch (error) {
        console.error(error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}

export async function OPTIONS(request: Request) {
    return NextResponse.json({}, { headers: { 'Allow': 'GET, OPTIONS' } });
}

