export interface ModuleApiParameter {
    name: string;
    type: string;
    description: string;
    optional?: boolean;
}

export interface ModuleApiEntry {
    name: string;
    kind: 'field' | 'function' | 'global';
    signature: string;
    description: string;
    parameters?: ModuleApiParameter[];
    returns?: string;
    contexts: Array<'server' | 'client'>;
    insertText?: string;
    example?: string;
    deprecated?: boolean;
}

export const moduleApiMetadata: ModuleApiEntry[] = [
    { name: 'Module', kind: 'field', signature: 'context.Module: ModuleMetadata', description: 'Published metadata and manifest for the currently running module project.', contexts: ['server', 'client'] },
    { name: 'Config', kind: 'field', signature: 'context.Config: ModuleConfigSchema', description: 'Configuration schema declared by the module manifest.', contexts: ['server', 'client'] },
    { name: 'Settings', kind: 'field', signature: 'context.Settings: { [string]: any }', description: 'Runtime module settings. Treat client values as presentation data, never as authority.', contexts: ['server', 'client'] },
    { name: 'Services', kind: 'field', signature: 'context.Services: WhitelistedServices', description: 'Context-appropriate Roblox services exposed by the Ro-Link runtime.', contexts: ['server', 'client'] },
    { name: 'Remotes', kind: 'field', signature: 'context.Remotes: { [string]: RoLinkRemote }', description: 'Module-scoped RemoteEvent and RemoteFunction wrappers with direction, schema, payload-size, and server rate-limit enforcement.', contexts: ['server', 'client'] },
    { name: 'UI', kind: 'field', signature: 'context.UI: { [string]: Instance? }', description: 'Read-only references to imported StarterGui objects. Access a root by name, then use normal Roblox child lookup.', contexts: ['client'] },
    { name: 'GetUI', kind: 'function', signature: 'context.GetUI(path: string): Instance?', description: 'Resolves an imported StarterGui reference in the local player PlayerGui. Use slash or dot-separated UI names.', parameters: [{ name: 'path', type: 'string', description: 'Imported UI name path, such as "Main/Hud".' }], returns: 'Instance?', contexts: ['client'], insertText: 'GetUI(${1:"Main/Hud"})' },
    { name: 'GetRemote', kind: 'function', signature: 'context.GetRemote(name: string): RoLinkRemote?', description: 'Returns a validated remote wrapper from this module namespace.', parameters: [{ name: 'name', type: 'string', description: 'Remote name declared in the project.' }], returns: 'RoLinkRemote?', contexts: ['server', 'client'], insertText: 'GetRemote(${1:"RemoteName"})' },
    { name: 'RegisterCommand', kind: 'function', signature: 'context.RegisterCommand(commandName: string, handler: (command, context, args) -> any)', description: 'Registers a server command handler.', parameters: [{ name: 'commandName', type: 'string', description: 'Unique command name.' }, { name: 'handler', type: 'function', description: 'Receives command, context, and args.' }], returns: '()', contexts: ['server'], insertText: 'RegisterCommand(${1:"command"}, function(command, commandContext, args)\n\t${0}\nend)' },
    { name: 'RegisterPanelCommand', kind: 'function', signature: 'context.RegisterPanelCommand(definition: PanelCommandDefinition, handler: function)', description: 'Registers a module command and exposes its metadata in the in-game Cmds panel.', parameters: [{ name: 'definition', type: 'PanelCommandDefinition', description: 'Title, description, category, target, and field metadata.' }, { name: 'handler', type: 'function', description: 'Runs when the panel command is submitted.' }], returns: '()', contexts: ['server'], insertText: 'RegisterPanelCommand({\n\tName = ${1:"command"},\n\tTitle = ${2:"Command"},\n\tDescription = ${3:""},\n}, function(command, commandContext, args)\n\t${0}\nend)' },
    { name: 'OnAdminPanelOpened', kind: 'function', signature: 'context.OnAdminPanelOpened(handler: (player: Player, payload: any, hookContext: any) -> ())', description: 'Runs when an authorized user opens the in-game admin panel.', parameters: [{ name: 'handler', type: 'function', description: 'Receives player, payload, and hook context.' }], returns: '()', contexts: ['server'], insertText: 'OnAdminPanelOpened(function(player, payload, hookContext)\n\t${0}\nend)' },
    { name: 'OnCommandBarOpened', kind: 'function', signature: 'context.OnCommandBarOpened(handler: (player: Player, payload: any, hookContext: any) -> ())', description: 'Runs when an authorized user opens the in-game command bar.', parameters: [{ name: 'handler', type: 'function', description: 'Receives player, payload, and hook context.' }], returns: '()', contexts: ['server'], insertText: 'OnCommandBarOpened(function(player, payload, hookContext)\n\t${0}\nend)' },
    { name: 'SendBotMessage', kind: 'function', signature: 'context.SendBotMessage(target: string, user: any?, channelId: string?, content: BotMessageContent): (boolean, any)', description: 'Sends a Discord bot message after validating the current server and target.', parameters: [{ name: 'target', type: '"channel" | "serverowner" | "user" | "dm" | "member"', description: 'Validated destination type.' }, { name: 'user', type: 'any?', description: 'Discord user identity for member or DM targets.', optional: true }, { name: 'channelId', type: 'string?', description: 'Channel belonging to the current Discord server.', optional: true }, { name: 'content', type: 'BotMessageContent', description: 'PlainText and/or Embed content.' }], returns: '(boolean, any)', contexts: ['server'], insertText: 'SendBotMessage(${1:"channel"}, ${2:nil}, ${3:channelId}, { PlainText = ${4:"Message"} })' },
    { name: 'GetDiscordChannels', kind: 'function', signature: 'context.GetDiscordChannels(): (boolean, { DiscordChannel })', description: 'Returns sendable Discord channels belonging to the current server.', returns: '(boolean, { DiscordChannel })', contexts: ['server'], insertText: 'GetDiscordChannels()' },
    { name: 'GetUserData', kind: 'function', signature: 'context.GetUserData(user: Player | string | number | table): (boolean, UserData)', description: 'Returns Roblox identity, role rank, and linked Discord member data.', parameters: [{ name: 'user', type: 'Player | string | number | table', description: 'Player, username, UserId, or identity table.' }], returns: '(boolean, UserData)', contexts: ['server'], insertText: 'GetUserData(${1:player})' },
    { name: 'GetReports', kind: 'function', signature: 'context.GetReports(options: ReportQuery?): (boolean, { Report })', description: 'Reads reports for the current Discord server.', parameters: [{ name: 'options', type: 'ReportQuery?', description: 'Optional status, limit, target, or reporter filters.', optional: true }], returns: '(boolean, { Report })', contexts: ['server'], insertText: 'GetReports({ status = ${1:"PENDING"}, limit = ${2:25} })' },
    { name: 'GetReport', kind: 'function', signature: 'context.GetReport(reportId: string): (boolean, Report)', description: 'Reads one report from the current Discord server.', parameters: [{ name: 'reportId', type: 'string', description: 'Report UUID.' }], returns: '(boolean, Report)', contexts: ['server'], insertText: 'GetReport(${1:reportId})' },
    { name: 'CreateReport', kind: 'function', signature: 'context.CreateReport(body: CreateReportInput): (boolean, Report)', description: 'Creates a pending report and snapshots live server information.', parameters: [{ name: 'body', type: 'CreateReportInput', description: 'Reporter, target, reason, and related report data.' }], returns: '(boolean, Report)', contexts: ['server'], insertText: 'CreateReport({\n\treportedUsername = ${1:player.Name},\n\treason = ${2:"Reason"},\n})' },
    { name: 'UpdateReport', kind: 'function', signature: 'context.UpdateReport(reportId: string, updates: UpdateReportInput): (boolean, Report)', description: 'Updates report status, notes, target, reason, or moderator fields.', parameters: [{ name: 'reportId', type: 'string', description: 'Report UUID.' }, { name: 'updates', type: 'UpdateReportInput', description: 'Validated fields to update.' }], returns: '(boolean, Report)', contexts: ['server'], insertText: 'UpdateReport(${1:reportId}, { status = ${2:"RESOLVED"} })' },
    { name: 'CreateUI', kind: 'function', signature: 'context.CreateUI(target: Player | string | number | { any }, functionOrTree: function | UiTree, props: table?): any', description: 'Creates module UI for one player, all players, or a target list.', parameters: [{ name: 'target', type: 'Player | string | number | { any }', description: 'Player, username, UserId, all/server/everyone, or a target list.' }, { name: 'functionOrTree', type: 'function | UiTree', description: 'Builder callback or supported serialized UI tree.' }, { name: 'props', type: 'table?', description: 'Optional root properties.', optional: true }], returns: 'any', contexts: ['server'], insertText: 'CreateUI(${1:player}, function(ui)\n\t${0}\nend)' },
    { name: 'FindPlayer', kind: 'function', signature: 'context.FindPlayer(target: Player | string | number): Player?', description: 'Finds one live player by instance, username, or UserId.', parameters: [{ name: 'target', type: 'Player | string | number', description: 'Player identity.' }], returns: 'Player?', contexts: ['server'], insertText: 'FindPlayer(${1:target})' },
    { name: 'GetPlayers', kind: 'function', signature: 'context.GetPlayers(): { Player }', description: 'Returns the current live Players list.', returns: '{ Player }', contexts: ['server'], insertText: 'GetPlayers()' },
    { name: 'Notify', kind: 'function', signature: 'context.Notify(target: Player | string | number, message: string, success: boolean?): ()', description: 'Shows admin-panel feedback to a player where the runtime feedback remote is available.', parameters: [{ name: 'target', type: 'Player | string | number', description: 'Player identity.' }, { name: 'message', type: 'string', description: 'Feedback text.' }, { name: 'success', type: 'boolean?', description: 'Success/error presentation.', optional: true }], returns: '()', contexts: ['server'], insertText: 'Notify(${1:player}, ${2:"Message"}, ${3:true})' },
    { name: 'Log', kind: 'function', signature: 'context.Log(...: any): ()', description: 'Prints a namespaced marketplace module log line.', parameters: [{ name: '...', type: 'any', description: 'Values to print.' }], returns: '()', contexts: ['server'], insertText: 'Log(${1:"Message"})' },
    { name: 'RoLinkModuleUI.Bind', kind: 'global', signature: '_G.RoLinkModuleUI.Bind(guiObject: GuiObject, handler: function, options: table?): ()', description: 'Binds client UI input from CreateUI instances back to server-side module code.', parameters: [{ name: 'guiObject', type: 'GuiObject', description: 'Object created by the module UI builder.' }, { name: 'handler', type: 'function', description: 'Receives player, payload, and instance.' }, { name: 'options', type: 'table?', description: 'Module metadata and allowed events.', optional: true }], returns: '()', contexts: ['server'], insertText: '_G.RoLinkModuleUI.Bind(${1:button}, function(player, payload, instance)\n\t${0}\nend)' },
];

export const moduleApiNames = new Set(moduleApiMetadata.filter((entry) => entry.name.indexOf('.') === -1).map((entry) => entry.name));
